development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9c662a52d0867ab583ddad3669ab50d6@porgy.redistogo.com:11568/
  channel_prefix: Loup-Garou_production
